# 
# Example config.  
#

# Default below
listen: :9000
banner: Secureweb VPN Portal

logout-url: https://google.co.uk
help-url: https://github.com/secureweb/openvpn-sso-portal/issues

fullname-header: X-Auth-Fullname
username-header: X-Auth-Username
roles-header: X-Auth-Roles

# Self-generated CA if not set.
# ca-certificate-file: tmp/ca/ca.pem
# ca-private-file: tmp/ca/ca-key.pem

# Used to drop OpenVPN profiles at startup.
# configdir-enabled: true
# configdir-path: /tmp/profiles

# 
profiles:
- name: livedata
  description : Live Data
  max-session: 2h
  roles:
    - vpn-livedata
  routes:
    - route: 192.168.1.0
      netmask: 255.255.255.0
  rules:
    - dest: 192.168.1.0/24
      port: 53
      protocol: tcp
      action: ACCEPT
- name: notlivedata
  description: Not Live Data
  max-session: 8h
  routes:
    - route: 172.16.0.0
      netmask: 255.255.255.0
  rules:
    - dest: 172.16.0.0/16
      port: 53
      protocol: udp
      action: ACCEPT
      
template: |
  #
  # Expiration of Certificate: {{ .Session.ExpiresOn }}
  # Session Duration: {{ .Session.Duration }}
  # VPN Profile for: {{ .Session.Profile }}
  #

  client
  dev tun
  proto udp
  remote openvpn.secureweb.ltd 1194
  resolv-retry infinite
  remote-cert-tls server
  nobind
  tls-version-min 1.2
  persist-key
  persist-tun
  ca [inline]
  cert [inline]
  key [inline]
  verb 1
  keepalive 10 900
  inactive 3600
  cipher AES-256-CBC
  tls-cipher TLS-ECDHE-RSA-WITH-AES-128-GCM-SHA256:TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256:TLS-ECDHE-RSA-WITH-AES-256-GCM-SHA384:TLS-DHE-RSA-WITH-AES-256-CBC-SHA256

  <ca>
  {{ .Session.IssuingCA }}</ca>

  <cert>
  {{ .Session.Certificate }}</cert>

  <key>
  {{ .Session.PrivateKey }}</key>
