apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "vpn-portal.fullname" . }}
  labels:
    app: {{ template "vpn-portal.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "vpn-portal.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "vpn-portal.fullname" . }}
    spec:
      containers:
      - name: oidc
        image: {{ .Values.image.oidc }}
        args:
        - --config=/etc/config/keycloak.yml
        ports:
        - name: http
          containerPort: 9000
        volumeMounts:
        - name: {{ template "vpn-portal.fullname" . }}-config
          mountPath: /etc/config
          readOnly: true
      - name: portal
        image: {{ .Values.image.portal }}
        args:
        - --config=/etc/config/portal.yml
        volumeMounts:
        - name: {{ template "vpn-portal.fullname" . }}-config
          mountPath: /etc/config
        - name: {{ template "vpn-portal.fullname" . }}-profiles
          mountPath: /tmp/openvpn/profiles
      - name: openvpn
        image: {{ .Values.image.openvpn }}
        env:
        - name: OPENVPN_CONFIG
          value: /etc/config/openvpn.conf
        - name: OPENVPN_DISABLE_FORWARDING
          value: "True"
        - name: OPENVPN_CLIENT_CONNECT
          value: /usr/local/bin/client_connected.sh
        - name: OPENVPN_CLIENT_DISCONNECT
          value: /usr/local/bin/client_disconnect.sh
        ports:
        - name: openvpn
          containerPort: 1194
        securityContext:
          capabilities:
            add:
              - SYS_ADMIN
              - NET_ADMIN
              - MKNOD
        volumeMounts:
        - name: {{ template "vpn-portal.fullname" . }}-config
          mountPath: /etc/config
          readOnly: true
        - name: {{ template "vpn-portal.fullname" . }}-profiles
          mountPath: /etc/openvpn/profiles
        - name: {{ template "vpn-portal.fullname" . }}-tls
          mountPath: /etc/tls
      volumes:
        - name: {{ template "vpn-portal.fullname" . }}-config
          configMap:
            name: {{ template "vpn-portal.fullname" . }}
            defaultMode: 0444
        - name: {{ template "vpn-portal.fullname" . }}-profiles
          emptyDir:
            defaultMode: 0777
        - name: {{ template "vpn-portal.fullname" . }}-tls
          emptyDir:
            defaultMode: 0777
