apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "vpn-portal.fullname" . }}
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "vpn-portal.fullname" . }}-portal
          servicePort: 9000

