apiVersion: v1
kind: Service
metadata:
  name: {{ template "vpn-portal.fullname" . }}-portal
spec:
  ports:
    - name: vpn
      port: {{ .Values.service.portal.externalPort }}
      targetPort: {{ .Values.service.portal.internalPort }}
  type: ClusterIP
  selector:
    app: {{ template "vpn-portal.fullname" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "vpn-portal.fullname" . }}
spec:
  ports:
    - name: vpn
      port: {{ .Values.service.openvpn.externalPort }}
      targetPort: {{ .Values.service.openvpn.internalPort }}
      proto: udp
  type: LoadBalancer
  selector:
    app: {{ template "vpn-portal.fullname" . }}
